### ISSUE TITLE
macos sequoia beta 

### ISSUE THREAD

**Issue by ykrem** [wflixu/typster#11]
Macos Version 15.0 Beta (24A5298h), app won't open, doesn't seem like disabling gatekeeper, or at least trying to, helps - still says
> “typster” is damaged and can’t be opened. You should move it to the Trash.

building instructions would be fine too ig, I'm a newbie but it's better than nothing :)

**Comment by wflixu** [comment]
you can try using xattr command

```shell
 xattr -c /Applications/typster.app

```

**Comment by ykrem** [comment]
It worked :D
